buildscript {
  ext.versions = [
      'minSdk': 16,
      'compileSdk': 27,
  ]

  repositories {
    mavenCentral()
    google()
    jcenter()
  }

  dependencies {
    classpath libs.android.gradlePlugin
    classpath libs.kotlin.gradlePlugin
    classpath libs.dokkaGradlePlugin
    classpath libs.gradleMavenPublishPlugin
  }
}

subprojects {
  repositories {
    mavenCentral()
    google()
    jcenter()
  }

  plugins.withId('org.jetbrains.kotlin.android') {
    kotlin {
      jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
      }
    }
  }

  plugins.withId('com.android.library') {
    android {
      compileSdkVersion versions.compileSdk

      defaultConfig {
        minSdkVersion versions.minSdk
      }

      compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
      }

      lintOptions {
        textOutput 'stdout'
        textReport true
      }
    }
  }

  tasks.withType(org.jetbrains.kotlin.gradle.dsl.KotlinCompile).configureEach { task ->
    task.kotlinOptions {
      freeCompilerArgs += [
        '-progressive',
      ]
    }
  }

  plugins.withId('com.vanniktech.maven.publish') {
    signing {
      def signingKey = findProperty('signingKey')
      def signingPassword = ''
      useInMemoryPgpKeys(signingKey, signingPassword)
    }
  }
}
