import com.vanniktech.maven.publish.MavenPublishBaseExtension

buildscript {
  ext.versions = [
      'minSdk': 16,
      'compileSdk': 31,
  ]

  repositories {
    mavenCentral()
    google()
  }

  dependencies {
    classpath libs.android.gradlePlugin
    classpath libs.kotlin.gradlePlugin
    classpath libs.dokkaGradlePlugin
    classpath libs.gradleMavenPublishPlugin
  }
}

subprojects {
  repositories {
    mavenCentral()
    google()
  }

  plugins.withId('com.android.library') {
    android {
      compileSdkVersion versions.compileSdk

      defaultConfig {
        minSdkVersion versions.minSdk
      }

      lintOptions {
        textOutput 'stdout'
        textReport true
      }
    }
  }

  tasks.withType(JavaCompile).configureEach { task ->
    task.sourceCompatibility = '1.8'
    task.targetCompatibility = '1.8'
  }

  tasks.withType(org.jetbrains.kotlin.gradle.dsl.KotlinCompile).configureEach { task ->
    task.kotlinOptions {
      jvmTarget = '1.8'
      freeCompilerArgs += [
        '-progressive',
      ]
    }
  }

  plugins.withId('com.vanniktech.maven.publish') {
    // Disable Javadoc jars. They're basically useless relics, but enabling this will also cause
    // AGP to use an old version of Dokka which fails to run on the latest Java versions.
    extensions.getByType(MavenPublishBaseExtension)
      .configureBasedOnAppliedPlugins(
        /* sourcesJar = */ true,
        /* javadocJar = */ false,
      )
  }
}
