apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'com.vanniktech.maven.publish'

dependencies {
  api project(':copper')
  api libs.kotlinx.coroutines.core
  api libs.androidx.annotation

  androidTestImplementation project(':copper-testing')
  androidTestImplementation libs.androidx.test.runner
  androidTestImplementation libs.assertk
  androidTestImplementation libs.turbine
}

android {
  namespace "app.cash.copper.flow"

  defaultConfig {
    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }
}
