name: release

on:
  push:
    tags:
      - '*'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  publish:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 19

      - run: ./gradlew build assembleAndroidTest

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          script: ./gradlew connectedCheck

      - name: Build and publish artifacts
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
        run: ./gradlew build publish

  github_release:
    runs-on: ubuntu-latest
    needs:
      - publish

    steps:
      - uses: actions/checkout@v3

      # Can only run on Linux.
      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
